name: Release

on:
  release:
    types: [published]
  push:
    branches: main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: --enable-preview --add-modules jdk.incubator.concurrent
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: 'openjdk@19.0.0=tgz+https://download.java.net/java/GA/jdk19/877d6127e982470ba2a7faa31cc93d04/36/GPL/openjdk-19_linux-x64_bin.tar.gz'
      - name: Setup GPG
        uses: olafurpg/setup-gpg@v3
      - name: Release new version
        run: sbt ci-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}